/*Contains the redux user action types*/

export const userConstants = {
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

  VERIFY_REQUEST: 'USER_VERIFY_REQUEST',
  VERIFY_SUCCESS: 'USER_VERIFY_SUCCESS',
  VERIFY_FAILURE: 'USER_VERIFY_FAILURE',

  PAGE_REFRESHED: 'PAGE_REFRESHED',

  LOGOUT: 'USER_LOGOUT',

  GETUSER_REQUEST: 'USER_GETUSER_REQUEST',
  GETUSER_SUCCESS: 'USER_GETUSER_SUCCESS',
  GETUSER_FAILURE: 'USER_GETUSER_FAILURE',
  GETUSER_CLEAR: 'USER_GETUSER_CLEAR',

  USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

  USER_BORROWER: 'USER_BORROWER',
  USER_BUILDER: 'USER_BUILDER',
  USER_LENDER: 'USER_LENDER',

  USER_PROFILE: 'USER_PROFILE',
  USER_NOPROFILE: 'USER_NOPROFILE'

};
